### PR TITLE
feat: Update block mapping to minecraft bedrock 1.20.10

### PR DESCRIPTION
**Pull request by smartcmd**
Since minecraft bedrock 1.20.10, mojang split concrete and shulker_box block into independent block ID

This PR synced changes made by mojang in minecraft bedrock 1.20.10

https://www.minecraft.net/zh-hans/article/1-20-10-update-available-bedrock

### CODE REVIEW

**Comment by onebeastchris** [comment]
This was already taken care off in https://github.com/GeyserMC/Geyser/commit/3a0c1b788a22492ac1068a2f2f17bab1cc995ef1 - there are specific methods to map concrete and shulker boxes to the new colors. 
As for the mappings themselves - they're not updated since Bedrock 1.20 is still supported, so instead of updating the mappings for all versions we're using per-version remappers (such as in the Item/Block registry) depending on protocol version.

Once the lowest supported version would be 1.20.10, we would update the mappings to be 1.20.10 native - until then, the current way would be used.

Thanks anyways!

**Comment by Konicai** [comment]
Did you test this with mappings-generator to make sure your changes aren't overridden?

**Comment by smartcmd** [comment]
> 

I'm not sure. I just write a simple script to make these changes c:

**Comment by smartcmd** [comment]
> 您是否使用映射生成器对此进行了测试，以确保您的更改不会被覆盖？

I'm not sure. I just wrote a simple script to make these changes

**Comment by smartcmd** [comment]
> Did you test this with mappings-generator to make sure your changes aren't overridden?

I'm not sure. I just wrote a simple script to make these changes

**Comment by Konicai** [comment]
Once we drop support for versions below 1.20.10, a PR to mappings-generator would be best to make these changes. Thank you though

**Pull request closed without merging**
