### PR TITLE
MIT relicense

### PR DESCRIPTION
**Pull request by RednedEpic**
Re-licenses the project under the MIT license. Will need permission from all contributors before this can be merged.

~~@DoctorMacc~~ ✓
~~@endevrr~~ ✓
~~@AJ-Ferguson~~ ✓
~~@rtm516~~ ✓
~~@D3ATHBRINGER13~~ ✓
~~@Arktisfox~~ ✓
~~@bundabrg~~ ✓ 
~~@davchoo~~ ✓ 
~~@jasoryeh~~ ✓ 
~~@OnlyBMan~~ ✓

All contributors will need to agree with this license being put on the project. If you do, please state so below.

### CODE REVIEW

**Comment by DoctorMacc** [comment]
I agree.

**Comment by OnlyBMan** [comment]
I agree 😄

**Comment by AJ-Ferguson** [comment]
I agree

**Comment by davchoo** [comment]
I agree.

**Comment by bundabrg** [comment]
agreed

**Comment by rtm516** [comment]
I agree

**Comment by D3ATHBRINGER13** [comment]
I agree

**Comment by D3ATHBRINGER13** [comment]
I agree

**Comment by endevrr** [comment]
I agree

**Comment by Arktisfox** [comment]
I agree

**Comment by jasoryeh** [comment]
I agree 💯

**Comment by RednedEpic** [comment]
Thanks!

**Pull request merged**
